[display]
cell_output = "below"
default_table_page_size = 10
theme = "light"
default_width = "medium"
code_editor_font_size = 14
reference_highlighting = false
dataframes = "rich"
default_table_max_columns = 50

[formatting]
line_length = 79

[experimental]

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[language_servers.ty]

[language_servers.basedpyright]

[language_servers.pylsp]
enable_mypy = true
enable_pyflakes = false
enable_pydocstyle = false
enable_ruff = true
enable_flake8 = false
enabled = true
enable_pylint = false

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = true

[ai]
mode = "manual"
inline_tooltip = false
rules = ""

[ai.models]
custom_models = []
displayed_models = []

[package_management]
manager = "uv"

[diagnostics]
sql_linter = true

[runtime]
output_max_bytes = 8000000
reactive_tests = true
watcher_on_save = "lazy"
on_cell_change = "autorun"
auto_instantiate = true
default_auto_download = []
auto_reload = "autorun"
default_sql_output = "auto"
std_stream_max_bytes = 1000000

[mcp]
presets = []

[mcp.mcpServers]

[snippets]
include_default_snippets = true
custom_paths = []

[server]
browser = "default"
follow_symlink = false

[completion]
activate_on_typing = true
copilot = false
